name: Continuous Integration

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
    types: [opened, synchronize, reopened]
  workflow_call:

permissions:
  contents: read

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/actions/checkout
      - name: Init Checkout
        uses: actions/checkout@v4

      # https://github.com/actions/setup-node
      - name: Set Up Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'

      - name: Install dependencies
        run: npm i

      - name: Build Node
        run: npm run build

      - name: set fake .env
        run: |
             touch .env
             echo "HOST=0.0.0.0" >> .env
             echo "LOG_LEVEL=info" >> .env
             echo "APP_KEY=1111-1111-1111-1111" >> .env

      - name: Run Tests
        run: npm run test

#      - name: Coverage
#        run: npm run test --coverage
