name: Create Release

on:
  workflow_dispatch:
    inputs:
      release-description:
        description: 'Release Description'
        required: true

jobs:
  build_and_test:
    uses: ./.github/workflows/ci.yml

#  todo sonar:
#    name: sonar
#    needs: build_and_test
#    runs-on: ubuntu-latest
#
#    steps:
#      # https://github.com/actions/checkout
#      - uses: actions/checkout@v4
#        with:
#          fetch-depth: 0  # Shallow clones should be disabled for a better relevancy of analysis
#
#      # https://github.com/SonarSource/sonarcloud-github-action
#      - name: Sonar Scan
#        uses: SonarSource/sonarcloud-github-action@master
#        env:
#          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}


  create_release:
    runs-on: ubuntu-latest
    needs: build_and_test

    steps:
      # https://github.com/actions/checkout
      - name: Init Checkout
        uses: actions/checkout@v4

      - name: Fetch Project Version
        id: extract_project_version
        run: |
          sudo apt-get update && sudo apt-get install jq
          version=$(jq -r '.version' package.json)
          echo "$version"
          echo "version=$version" >> $GITHUB_OUTPUT

      # https://github.com/actions/create-release
      - name: Create Release On Github
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.extract_project_version.outputs.version }}
          release_name: Release ${{ steps.extract_project_version.outputs.version }}
          body: |
            ${{ inputs.release-description }}
          draft: false
          prerelease: false

#  build_image_and_deploy_it:
#    needs: create_release
#    runs-on: ubuntu-latest
#
#    env:
#      DOCKERFILE: Dockerfile
#      REPOSITORY: ${{ secrets.DOCKER_HUB_REGISTRY }}/codenshare-api
#
#    steps:
#      - name: Chek env
#        run : echo $TEST
#      - uses: actions/checkout@v4
#
#      # https://github.com/docker/login-action
#      - name: Log in to Docker Hub
#        uses: docker/login-action@v3
#        with:
#          username: ${{ secrets.DOCKER_HUB_LOGIN }}
#          password: ${{ secrets.DOCKER_HUB_TOKEN }}
#
#        # https://github.com/docker/build-push-action
#      - name: Push Docker image with release version
#        uses: docker/build-push-action@v5
#        with:
#          context: .
#          file: Dockerfile
#          push: true
#          tags: ${{ env.REPOSITORY }}:${{ steps.fetch_project_version.outputs.version }}
